
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "EcheAdmin",
    "password": "byron"
}

########USERS########

GET http://localhost:3000/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###

GET http://localhost:3000/users/34
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###

POST  http://localhost:3000/users
Content-Type: application/json

{
    "username": "Marce",
    "name": "Marcela",
    "surname": "Lopez",
    "email": "marce@gmail.com",
    "address": "Direccion inventada 123",
    "phone_number": 1160001234,
    "address": "Calle 123",
    "password": "byron",
    "is_admin": false
}

########PRODUCTS########

POST  http://localhost:3000/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

{
    "name": "Ensalada",
    "price": 400,
    "img_url": "https://mahatmarice.com/wp-content/uploads/2020/04/Rice-Pizza-Crust.jpg"
}

###

GET http://localhost:3000/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###

GET http://localhost:3000/products/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###DELETE

DELETE http://localhost:3000/products/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###UPDATE

PATCH http://localhost:3000/products/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

{
    "name": "Pizza Pepperoni",
    "price": 600,
    "img_url": "https://mahatmarice.com/wp-content/uploads/2020/04/Rice-Pizza-Crust.jpg"
}


########ORDERS########

//CREAR ORDENES

POST  http://localhost:3000/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

{
        "id_pay_method": 2,
        "products":[
            {
            "id_product": 10,
            "quantity": 3
        },
                    {
            "id_product": 9,
            "quantity": 3
        }
        ] 

}

###

//LISTAR ORDENES
GET  http://localhost:3000/orders
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###

//LISTAR PRODUCTOS DE UNA ORDEN
GET  http://localhost:3000/orders/31/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###


//UPDATE STATUS

PATCH  http://localhost:3000/orders/25
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNSwidXNlcm5hbWUiOiJFY2hlQWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE0ODA0NjY3fQ.hN5EFiV2Cr21g12porst-65hwam7pJntzz4tVla-cPw

{
        "id_status": 2

}

###

//DELETE ORDER

DELETE  http://localhost:3000/orders/27
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNSwidXNlcm5hbWUiOiJFY2hlQWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE0ODA0NjY3fQ.hN5EFiV2Cr21g12porst-65hwam7pJntzz4tVla-cPw

