
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "maria",
    "password": "admin"
}

########USERS########

GET http://localhost:3000/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###

GET http://localhost:3000/users/34
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###

POST  http://localhost:3000/users
Content-Type: application/json

{
    "username": "maria",
    "name": "Maria",
    "surname": "Doe",
    "email": "Maria@gmail.com",
    "address": "Calle Falsa 123",
    "phone_number": 1160001234,
    "address": "Calle 123",
    "password": "admin",
    "is_admin": true
}

########PRODUCTS########

POST  http://localhost:3000/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6Im1hcmlhIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTYxNTIxMzE4Nn0.z-WkQ0ZHZScyFWhP8hl_LTqZRXH-nevKBKeeRuiTGtE

{
    "name": "Hamburguesa",
    "price": 500,
    "img_url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fcomputerhoy.com%2Fnoticias%2Flife%2Fhamburguesa-cara-mundo-cuesta-5000-dolares-776715&psig=AOvVaw2kzEY1-fQZPFy2K8TH-Act&ust=1615299674125000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJj1h6ryoO8CFQAAAAAdAAAAABAD"
}

###

GET http://localhost:3000/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###

GET http://localhost:3000/products/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###DELETE

DELETE http://localhost:3000/products/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNSwidXNlcm5hbWUiOiJFY2hlQWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE0OTU2NDc5fQ.hN8u_UflHDWloR6WwNK2YLBA_1bz-VVovawaOI0TpnY

###UPDATE

PATCH http://localhost:3000/products/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

{
    "name": "Pizza Pepperoni",
    "price": 600,
    "img_url": "https://mahatmarice.com/wp-content/uploads/2020/04/Rice-Pizza-Crust.jpg"
}


########ORDERS########

//CREAR ORDENES

POST  http://localhost:3000/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

{
        "id_pay_method": 2,
        "products":[
            {
            "id_product": 16,
            "quantity": 1
        },
            {
            "id_product": 17,
            "quantity": 1
        }
        ] 

}

###

//LISTAR ORDENES
GET  http://localhost:3000/orders
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ

###

//LISTAR PRODUCTOS DE UNA ORDEN
GET  http://localhost:3000/orders/39/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNCwidXNlcm5hbWUiOiJFY2hlIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTQ3NzczMTZ9.2S4IfNiOWg-qOFilRilzm1aCxjZ2z-tuPAwhejO1AwQ
###


//UPDATE STATUS

PATCH  http://localhost:3000/orders/25
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNSwidXNlcm5hbWUiOiJFY2hlQWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE0ODA0NjY3fQ.hN5EFiV2Cr21g12porst-65hwam7pJntzz4tVla-cPw

{
        "id_status": 2

}

###

//DELETE ORDER

DELETE  http://localhost:3000/orders/27
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjozNSwidXNlcm5hbWUiOiJFY2hlQWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE0ODA0NjY3fQ.hN5EFiV2Cr21g12porst-65hwam7pJntzz4tVla-cPw

